backend:
  name: github
  repo: Dorsey2121/hair-by-janice
  branch: gh-pages

media_folder: "images/uploads"

collections:


  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "_data/home.yml"
        fields:
          - label: "Banner 1"
            name: "banner-1"
            widget: "object"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Text"
                name: "text"
                widget: "string"
              - label: "Button"
                name: "button"
                widget: "string"
              - label: "Image"
                name: "image"
                widget: "image"

          - label: "Banner 2"
            name: "banner-2"
            widget: "object"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Text"
                name: "text"
                widget: "string"
              - label: "Button"
                name: "button"
                widget: "string"
              - label: "Image"
                name: "image"
                widget: "image"

          - label: "Banner 3"
            name: "banner-3"
            widget: "object"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Text"
                name: "text"
                widget: "string"
              - label: "Button"
                name: "button"
                widget: "string"
              - label: "Image"
                name: "image"
                widget: "image"

          - label: "About section"
            name: "about"
            widget: "object"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Text"
                name: "text"
                widget: "string"

          - label: "Testimonials"
            name: "testimonials"
            widget: "object"
            fields:
              - label: "Text-1"
                name: "text-1"
                widget: "string"
              - label: "Text-2"
                name: "text-2"
                widget: "string"
              - label: "Text-2"
                name: "text-2"
                widget: "string"
              - label: "Text-2"
                name: "text-2"
                widget: "string"


      - label: "Book Page"
        name: "book-appointment"
        file: "_data/book-appointment.yml"
        fields:
          - label: "Banner book"
            name: "banner-book"
            widget: "object"
            fields:
              - label: "Image"
                name: "image"
                widget: "image"

          - label: "Intro"
            name: "intro-text"
            widget: "object"
            fields:
              - label: "Text"
                name: "text"
                widget: "string"


  - label: "Blog"
    name: "blog"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: "Image"
        name: "image"
        widget: "image"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Preview Text"
        name: "preview-text"
        widget: "string"
      - label: "Article Text"
        name: "body"
        widget: "markdown"
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "blog-posts"

  - label: "Gallery"
    name: "gallery"
    files:
      - label: "Gallery"
        name: "gallery"
        file: _data/gallery.yml
        fields:
          - label: "Gallery"
            name: "gallery"
            widget: "list"
            fields:
              - label: "Photo Descriptiom"
                name: "alttext"
                widget: "string"
              - label: "Image"
                name: "image"
                widget: "image"


  - label: "Gallery"
    name: "gallery"
    files:
      - label: "Gallery"
        name: "gallery"
        file: _data/gallery.yml
        fields:
          - label: "Gallery"
            name: "gallery"
            widget: "list"
            fields:
              - label: "Photo Descriptiom"
                name: "alttext"
                widget: "string"
              - label: "Image"
                name: "image"
                widget: "image"
