backend:
  name: github
  repo: Dorsey2121/hair-by-janice
  branch: gh-pages

media_folder: "images/uploads"

collections:
  - label: "Footer Content"
    name: "footer"
    files:
      - label: "Hours"
        name: "hours"
        file: "_data/footer.yml"
        fields:
          - label: "Hours"
            name: "hours"
            widget: "object"
            fields:
              - label: "Monday"
                name: "monday"
                widget: "string"
              - label: "Tuesday"
                name: "tuesday"
                widget: "string"
              - label: "Wednesday"
                name: "wednesday"
                widget: "string"
              - label: "Thursday"
                name: "thursday"
                widget: "string"
              - label: "Friday"
                name: "friday"
                widget: "string"
              - label: "Saturday"
                name: "saturday"
                widget: "string"
              - label: "Sunday"
                name: "sunday"
                widget: "string"

          - label: "Contact"
            name: "contact"
            widget: "fields"
            fields:
              - label: "Street"
                name: "street"
                widget: "string"
              - label: "Suite"
                name: "suite"
                widget: "string"
              - label: "City"
                name: "city"
                widget: "string"
              - label: "Tel"
                name: "tel"
                widget: "string"
              - label: "Email"
                name: "email"
                widget: "string"

          - label: "Social Media"
            name: "social-media"
            widget: "objects"
            fields:
              - label: "Facebook"
                name: "facebook"
                widget: "string"
              - label: "Instagram"
                name: "instagram"
                widget: "string"


  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "_data/home.yml"
        fields:
          - label: "Banner 1"
            name: "banner-1"
            widget: "object"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Text"
                name: "text"
                widget: "string"
              - label: "Button"
                name: "button"
                widget: "string"
              - label: "Image"
                name: "image"
                widget: "image"

          - label: "Banner 2"
            name: "banner-2"
            widget: "object"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Text"
                name: "text"
                widget: "string"
              - label: "Button"
                name: "button"
                widget: "string"
              - label: "Image"
                name: "image"
                widget: "image"

          - label: "Banner 3"
            name: "banner-3"
            widget: "object"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Text"
                name: "text"
                widget: "string"
              - label: "Button"
                name: "button"
                widget: "string"
              - label: "Image"
                name: "image"
                widget: "image"

          - label: "About section"
            name: "about"
            widget: "object"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Text"
                name: "text"
                widget: "string"

          - label: "Testimonials"
            name: "testimonials"
            widget: "object"
            fields:
              - label: "Text-1"
                name: "text-1"
                widget: "string"
              - label: "Text-2"
                name: "text-2"
                widget: "string"
              - label: "Text-3"
                name: "text-3"
                widget: "string"
              - label: "Text-4"
                name: "text-4"
                widget: "string"
              - label: "Image"
                name: "image"
                widget: "image"


      - label: "Book Page"
        name: "book-appointment"
        file: "_data/book-appointment.yml"
        fields:
          - label: "Banner book"
            name: "banner-book"
            widget: "object"
            fields:
              - label: "Image"
                name: "image"
                widget: "image"

          - label: "Intro"
            name: "intro-text"
            widget: "object"
            fields:
              - label: "Text"
                name: "text"
                widget: "string"


      - label: "Blog"
        name: "blog"
        folder: "_posts"
        create: true
        slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
        fields:
          - label: "Image"
            name: "image"
            widget: "image"
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Preview Text"
            name: "preview-text"
            widget: "string"
          - label: "Article Text"
            name: "body"
            widget: "markdown"
          - label: "Layout"
            name: "layout"
            widget: "hidden"
            default: "blog-posts"


      - label: "Gallery"
        name: "gallery"
        file: _data/gallery.yml
        fields:
          - label: "Gallery"
            name: "gallery"
            widget: "list"
            fields:
              - label: "Photo Description"
                name: "alttext"
                widget: "string"
              - label: "Image"
                name: "image"
                widget: "image"



      - label: "Services"
        name: "services"
        file: _data/services.yml
        fields:
          - label: "Services"
            name: "service"
            widget: "list"
            fields:
              - label: "Service"
                name: "service"
                widget: "string"
              - label: "Price"
                name: "price"
                widget: "string"
              - label: "Description"
                name: "description"
                widget: "string"
